substitutions:
  device_name: garage_left_bay
  upper_device_name: Garage Left Bay
  timeout: 2.7m  #greater than garage height
  max_distance: "2.65" #actual height of garage

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi_iot.yaml

mqtt: !include include/mqtt.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: INFO

# # Enable Home Assistant API
# api:

ota:

sensor:
  - platform: ultrasonic
    name: $upper_device_name HC-SR04
    trigger_pin: D1
    echo_pin: D2
    timeout: $timeout
    id: ultra_sensor
    update_interval: 500ms
    filters:
      ## Catch NAN and replace with max distance
      - lambda:
          if (isnan(x)) return $max_distance;
          return x;
      - exponential_moving_average:
          alpha: 0.1
          send_every: 10
      - delta: 0.1

  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 30min
    icon: mdi:wifi

binary_sensor:
  - platform: template
    name: $upper_device_name
    lambda: |-
      if (id(ultra_sensor).state < 1.2 ) { // in meters
        // Truck is in.
        return true;
      } else {
        // truck is out
        return false;
      }
      
button:
  - platform: restart
    name: $upper_device_name Restart