substitutions:
  device_name: garage_temp_3
  upper_device_name: Garage Temp 3
  ip_address: 192.168.37.211

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi_iot_manual.yaml

captive_portal:

web_server:
  port: 80

logger:
  level: DEBUG

ota:
  platform: esphome

# web_server:
#   port: 80

mqtt: !include include/mqtt_deep_sleep.yaml

# Enable Home Assistant API
# api:

i2c:

sensor:

  - !include include/bme280.yaml

  - platform: adc
    pin: A0
    filters:
      - multiply: 126.105740765398
    unit_of_measurement: "%"
    name: $upper_device_name Battery
    device_class: battery
    update_interval: 60s
    expire_after: 30min
    state_topic: $device_name/battery/state

  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    expire_after: 60min
    icon: mdi:wifi
  
button:
  - platform: restart
    name: $upper_device_name Restart
    
deep_sleep: !include include/deep_sleep_15.yaml
