substitutions:
  device_name: laundry_motion
  upper_device_name: Laundry Motion

esphome:
  name: $device_name

esp8266:
  board: d1_mini

wifi: !include include/wifi_iot.yaml

captive_portal:

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:
  platform: esphome

mqtt: !include include/mqtt.yaml

binary_sensor:
  - !include include/pir_GPIO13.yaml
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 30min
    icon: mdi:wifi
      
button:
  - platform: restart
    name: $upper_device_name Restart
