substitutions:
  device_name: lr
  upper_device_name: Living Room
  ip_address: 192.168.37.212

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi_iot_manual.yaml

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
# api:

ota:
  platform: esphome

web_server:
  port: 80

mqtt: !include include/mqtt_deep_sleep.yaml

i2c:

sensor:
  - !include include/sht3xd-45.yaml

  # - platform: adc
  #   pin: A0
  #   filters:
  #     - multiply: 4.111111
  #   name: $upper_device_name Battery
  #   device_class: battery
  #   update_interval: 60s
  #   expire_after: 30min
  #   state_topic: $device_name/battery/state

  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    
deep_sleep: !include include/deep_sleep_15.yaml
      
button:
  - platform: restart
    name: $upper_device_name Restart