substitutions:
  device_name: lr_ir
  upper_device_name: Living Room IR
  switch_prefix: IR

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi_iot.yaml

captive_portal:

web_server:
  port: 80
  include_internal: true

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
    
# output: !include include/onboard_led.yaml

binary_sensor:
  - platform: template
    name: $upper_device_name State
    id: lr_tv_state
    icon: mdi:television
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 30min
    icon: mdi:wifi

text_sensor:    
  - platform: homeassistant
    id: hass_lr_tv_status
    entity_id: sensor.living_room_tv_status
    internal: true
    on_value:
      then:
        - if:
            condition:
              text_sensor.state:
                id: hass_lr_tv_status
                state: 'On'
            then: 
              lambda: id(lr_tv_state).publish_state(true);
            else:
              lambda: id(lr_tv_state).publish_state(false);
      
script: 
  # While this script is running the receiver will ignore any power codes
  - id: code_repeat_block
    then:
      - delay: 1.5s
      
remote_receiver:
  pin:
    number: GPIO2 # D4
    inverted: true
    mode:
      input: true
      pullup: true
  # dump: all
  on_sony:
    lambda: |-
      if (x.data == 0xA90){
        if ( id(code_repeat_block).is_running() == false){
          id(code_repeat_block).execute();
          if (id(lr_tv_state).state) {
            id(lr_tv_state).publish_state(false);
          } else {
            id(lr_tv_state).publish_state(true);
          }
        }
      }
    
remote_transmitter:
  pin: GPIO0  # D3
  carrier_duty_percent: 50%
  id: trans
      
button:
  - platform: restart
    name: $upper_device_name Restart
    
  - platform: template
    name: $upper_device_name Sony TV Power
    on_press:
      remote_transmitter.transmit_sony:
        data: 0xA90
        nbits: 12
        repeat:
          times: 2
    
  - platform: template
    name: $upper_device_name Sony TV Mute
    on_press:
      remote_transmitter.transmit_sony:
        data: 0x290
        nbits: 12
        repeat:
          times: 2
    
  - platform: template
    name: $upper_device_name Cablebox
    id: cablebox
    on_press:
      remote_transmitter.transmit_sony:
        data: 0x250
        nbits: 12
        repeat:
          times: 2
    
  - platform: template
    name: $upper_device_name Netflix
    on_press:
      # Netflix button
      - remote_transmitter.transmit_sony:
          data: 0x1F58
          nbits: 15
          repeat:
            times: 2
      - delay: 1000ms
      # OK
      - remote_transmitter.transmit_sony:
          data: 0xA70
          nbits: 12
          repeat:
            times: 2
    
  - platform: template
    name: $upper_device_name TV-Cable On
    id: tv_cable_on
    on_press:
        #. TV power on, Cable Menu, Cable power twice
      - if:
          condition:
            # Checks if tv is already on
            binary_sensor.is_off: lr_tv_state
          then:
            - remote_transmitter.transmit_sony:
                data: 0xA90
                nbits: 12
                repeat:
                  times: 2
            - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8989, -4488, 502, -4489, 505, -2225, 505, -2232, 475, -4515, 
                  476, -4518, 500, -2236, 496, -2227, 506, -2228, 505, -2228, 
                  505, -2229, 503, -2229, 502, -2231, 502, -2231, 501, -4491, 
                  500, -4490, 502, -2228, 505]
          carrier_frequency: 38kHz
      - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8900,-4300, 600,-2150, 600,-4300, 600,-2100, 600,-4350, 600,-2150, 
                 600,-2150, 600,-2150, 600,-2100, 600,-2150, 600,-2150, 600,-2150,
                 600,-2150, 600,-2150, 600,-4300, 600,-4300, 600,-2150, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8900,-4300, 600,-2150, 600,-4300, 600,-2100, 600,-4350, 600,-2150, 
                 600,-2150, 600,-2150, 600,-2100, 600,-2150, 600,-2150, 600,-2150,
                 600,-2150, 600,-2150, 600,-4300, 600,-4300, 600,-2150, 600]
          carrier_frequency: 38kHz
    
  - platform: template
    name: $upper_device_name TV-Cable Off
    id: tv_cable_off
    on_press:
        #. TV power on, Cable Menu, Cable power one
      - if:
          condition:
            # Only turn off the TV if it is actually on
            binary_sensor.is_on: lr_tv_state
          then:
            - remote_transmitter.transmit_sony:
                data: 0xA90
                nbits: 12
                repeat:
                  times: 2
            - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8989, -4488, 502, -4489, 505, -2225, 505, -2232, 475, -4515, 
                  476, -4518, 500, -2236, 496, -2227, 506, -2228, 505, -2228, 
                  505, -2229, 503, -2229, 502, -2231, 502, -2231, 501, -4491, 
                  500, -4490, 502, -2228, 505]
          carrier_frequency: 38kHz
      - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8900,-4300, 600,-2150, 600,-4300, 600,-2100, 600,-4350, 600,-2150, 
                 600,-2150, 600,-2150, 600,-2100, 600,-2150, 600,-2150, 600,-2150,
                 600,-2150, 600,-2150, 600,-4300, 600,-4300, 600,-2150, 600]
          carrier_frequency: 38kHz
    
  - platform: template
    name: $upper_device_name TV All On Off
    id: lr_tv_all_on_off
    on_press:
      - if:
          condition:
            binary_sensor.is_on: lr_tv_state
          then:
            - button.press: tv_cable_off
          else:
            - button.press: tv_cable_on
    
  - platform: template
    name: $upper_device_name CNN
    # Channel 33
    on_press:
      - if:
          condition:
            # We need the TV on first
            binary_sensor.is_off: lr_tv_state
          then:
            - button.press: tv_cable_on
            - delay: 3s
      - remote_transmitter.transmit_raw:
          # Digit 3
          code: [ 9100,-4450, 600,-4450, 550,-4500, 600,-2200, 550,-2200, 550,-2200, 
                  550,-2200, 550,-2250, 550,-2250, 550,-2200, 600,-2200, 550,-2200, 
                  550,-2200, 550,-4450, 600,-2200, 550,-4450, 600,-4450, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
      - remote_transmitter.transmit_raw:
          # Digit 3
          code: [ 9100,-4450, 600,-4450, 550,-4500, 600,-2200, 550,-2200, 550,-2200, 
                  550,-2200, 550,-2250, 550,-2250, 550,-2200, 600,-2200, 550,-2200, 
                  550,-2200, 550,-4450, 600,-2200, 550,-4450, 600,-4450, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
      - button.press: cablebox
    
  - platform: template
    name: $upper_device_name Science Channel
    # Channel 76
    on_press:
      - if:
          condition:
            # We need the TV on first
            binary_sensor.is_off: lr_tv_state
          then:
            - button.press: tv_cable_on
            - delay: 3s
      - remote_transmitter.transmit_raw:
          # Digit 7
          code: [ 9100,-4450, 600,-4450, 600,-4450, 600,-4450, 600,-2200, 600,-2200, 
                  600,-2200, 550,-2200, 600,-2200, 600,-2200, 600,-2200, 600,-2200, 
                  600,-2200, 600,-4450, 600,-2200, 600,-2200, 600,-4450, 550]
          carrier_frequency: 38kHz
      - delay: 300ms
        # Digit 6
      - remote_transmitter.transmit_raw:
          code: [ 9100,-4450, 550,-2200, 600,-4450, 600,-4500, 600,-2200, 600,-2200, 
                  600,-2200, 550,-2200, 600,-2200, 600,-2200, 600,-2200, 600,-2200, 
                  550,-2200, 600,-2200, 600,-4450, 600,-2200, 550,-4450, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
      - button.press: cablebox
    
  - platform: template
    name: $upper_device_name NBC
    # Channel 4
    on_press:
      - if:
          condition:
            # We need the TV on first
            binary_sensor.is_off: lr_tv_state
          then:
            - button.press: tv_cable_on
            - delay: 3s
      - remote_transmitter.transmit_raw:
          # Digit 4
          code: [ 9100,-4450, 600,-2200, 550,-2200, 550,-4450, 600,-2200, 550,-2200, 
                  550,-2200, 550,-2200, 550,-2250, 550,-2250, 550,-2200, 600,-2200, 
                  550,-2200, 550,-2200, 550,-2200, 550,-4500, 600,-4450, 550]
          carrier_frequency: 38kHz
      - delay: 300ms
      - button.press: cablebox
    
  - platform: template
    name: $upper_device_name CBS
    # Channel 10
    on_press:
      - if:
          condition:
            # We need the TV on first
            binary_sensor.is_off: lr_tv_state
          then:
            - button.press: tv_cable_on
            - delay: 3s
      - remote_transmitter.transmit_raw:
          # Digit 1
          code: [ 9050,-4500, 600,-4450, 600,-2200, 600,-2250, 550,-2200, 550,-2200, 
                  600,-2200, 600,-2200, 600,-2200, 550,-2200, 550,-2200, 600,-2200, 
                  550,-2200, 600,-4450, 600,-4450, 600,-4450, 600,-4450, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
        # Digit 0
      - remote_transmitter.transmit_raw:
          code: [ 9100,-4450, 600,-2200, 550,-2200, 550,-2250, 550,-2200, 550,-2200, 
                  550,-2250, 550,-2200, 550,-2200, 550,-2250, 550,-2200, 600,-2200, 
                  550,-2250, 550,-2200, 550,-2200, 550,-2200, 550,-2200, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
      - button.press: cablebox
    
  - platform: template
    name: $upper_device_name ABC
    # Channel 8
    on_press:
      - if:
          condition:
            # We need the TV on first
            binary_sensor.is_off: lr_tv_state
          then:
            - button.press: tv_cable_on
            - delay: 3s
      - remote_transmitter.transmit_raw:
          # Digit 8
          code: [ 9100,-4450, 600,-2200, 600,-2200, 600,-2200, 600,-4450, 600,-2200, 
                  600,-2200, 600,-2200, 600,-2200, 600,-2200, 600,-2200, 600,-2200, 
                  550,-2200, 600,-2200, 600,-2200, 600,-2200, 550,-4500, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
      - button.press: cablebox
          

  

  
  
  
  
  