substitutions:
  name: m5stack-atom-echo-8a2758
  friendly_name: M5Stack Atom Echo 8a2758
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: KofOlsHqtzOgOkyDFT3GyQxKcWYJApP4WUgz0VwZzQ8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
