substitutions:
  upper_device_name: Office AC Receiver
  device_name: of_ac_rcvr 

esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

ota:
  platform: esphome

wifi: !include include/wifi_iot.yaml

captive_portal:

mqtt: !include include/mqtt.yaml
    
remote_receiver:
  pin: 
    number: GPIO2
    inverted: True
  dump: nec
  id: recvr1
  
binary_sensor:
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Power Button"
    nec:
      address: 0xFF01
      command: 0xED12
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Temp Plus"
    nec:
      address: 0xFF01
      command: 0xE51A
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Temp Minus"
    nec:
      address: 0xFF01
      command: 0xEC13
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Eco"
    nec:
      address: 0xFF01
      command: 0xF00F
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Display"
    nec:
      address: 0xFF01
      command: 0x9966
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Fan"
    nec:
      address: 0xFF01
      command: 0xF10E
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Mode"
    nec:
      address: 0xFF01
      command: 0xFD02
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Timer"
    nec:
      address: 0xFF01
      command: 0xE41B
      
  - platform: remote_receiver
    receiver_id: recvr1
    name: "Office AC Sleep"
    nec:
      address: 0xFF01
      command: 0xF50A
      
button:
  - platform: restart
    name: $upper_device_name Restart