substitutions:
  device_name: of_ac
  upper_device_name: Office AC

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi_iot.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:
  platform: esphome

mqtt: !include include/mqtt.yaml
    
output: !include include/onboard_led.yaml
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 30min
    icon: mdi:wifi
      
remote_transmitter:
  pin: GPIO04
  carrier_duty_percent: 50%
  id: remote_1

# Individual buttons
button:
  - platform: template
    name: Office AC Power
    id: power
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xED12
      - output.turn_on: onboard_led
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Mode
    id: mode
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xFD02
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Minus
    id: minus
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xEC13
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Plus
    id: plus
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xE51A
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Timer
    id: timer
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xE41B
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Fan
    id: fan
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xF10E
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Eco
    id: eco
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xf00f
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Display
    id: display
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0x9966
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: template
    name: Office AC Sleep
    id: sleepy
    on_press:
      - output.turn_on: onboard_led
      - remote_transmitter.transmit_nec:
          address: 0xFF01
          command: 0xF50A
      - delay: 250ms
      - output.turn_off: onboard_led
      
  - platform: restart
    name: $upper_device_name Restart
      
      