substitutions:
  device_name: office
  upper_device_name: Office
  ip_address: 192.168.37.203

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi_iot_manual.yaml

captive_portal:

# Enable logging
logger:
  level: WARN
  
# Enable Home Assistant API
# api:

ota:

web_server:
  port: 80

mqtt: !include include/mqtt_deep_sleep.yaml
      
i2c:

sensor:

  - !include include/bme280.yaml

  - platform: adc
    pin: A0
    filters:
      - multiply: 100
      - median:
          window_size: 7
          send_every: 2
          send_first_at: 1
    unit_of_measurement: "%"
    name: $upper_device_name Battery
    device_class: battery
    update_interval: 60s
    expire_after: 60min
    state_topic: $device_name/battery/state

  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    
deep_sleep: !include include/deep_sleep_15.yaml
      
button:
  - platform: restart
    name: $upper_device_name Restart