substitutions:
  device_name: outdoor
  upper_device_name: Outdoor
  ip_address: 192.168.37.213

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini_pro
  on_boot:
    - priority: 500.00
      then:
        - delay: 500ms

wifi: !include include/wifi_iot_manual.yaml

captive_portal:

# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
# api:

ota:
  platform: esphome

web_server:
  port: 80

mqtt:  !include include/mqtt_deep_sleep_device_name.yaml

i2c:

sensor:
  - !include include/sht3xd.yaml
    
  # - platform: ms5611
  #   temperature:
  #     name: $upper_device_name Alt Temperature
  #     id: alt_temperature
  #     # internal: true
  #   pressure:
  #     name: $upper_device_name Pressure
  #     id: pressure
  #     expire_after: 30min
  #     unit_of_measurement: "mbar"
  #     device_class: pressure
  #     accuracy_decimals: 2
  #     state_topic: $device_name/pressure/state
  #   address: 0x77
  #   update_interval: 60s

  - platform: adc
    pin: A0
    filters:
      - multiply: 100
      - median:
          window_size: 7
          send_every: 2
          send_first_at: 1
    unit_of_measurement: "%"
    name: $upper_device_name Battery
    id: battery
    device_class: battery
    update_interval: 60s
    expire_after: 60min
    state_topic: $device_name/battery/state

  - platform: wifi_signal
    id: wifi_signal_1
    name: $upper_device_name WiFi Signal
    expire_after: 60min
    update_interval: 60s
    
deep_sleep: !include include/deep_sleep_15.yaml
      
button:
  - platform: restart
    name: $upper_device_name 
    id: restart_button

